services:
  database:
    container_name: mysql
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: antennadb
      MYSQL_USER: gorilla
      MYSQL_PASSWORD: gorilla
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: a305!
      TZ: "Asia/Seoul"
    ports:
      - 4444:3306
    restart: unless-stopped
    volumes:
      - /antenna-data:/var/lib/mysql

  backend:
    build:
      context: ./backend/antenna/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - database
    container_name: springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:4444/antennadb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: gorilla
      SPRING_DATASOURCE_PASSWORD: gorilla
      TZ: "Asia/Seoul"
  
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    restart: on-failure
    container_name: react
    environment:
      TZ: "Asia/Seoul"
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - backend

  nginx:
    container_name: nginx
    image: nginx:1.22.1
    restart: always
    volumes:
      - ./frontend/conf/:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      TZ: "Asia/Seoul"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
